# Generated by Django 4.0 on 2021-12-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainings',
            new_name='Training',
        ),
    ]
